### ISSUE TITLE
zcat error issue

### ISSUE THREAD

**Issue by piotrsmykaj** [ec-europa/ssk#173]
Error in `drush-sql-import` phing target on macOS Mojave:

`zcat: can't stat: /tmp/toolkit/subsites/packages/database/betapolitical/sanitized_daily_multisite_betapolitical_production.sql.gz (/tmp/toolkit/subsites/packages/database/betapolitical/sanitized_daily_multisite_betapolitical_production.sql.gz.Z): No such file or directory`

The issue described here: 
https://stackoverflow.com/questions/296717/zcat-wont-unzip-files-properly

With `gzcat` it works well.

**Comment by ghost** [comment]
Released in 3.0.23: https://github.com/ec-europa/toolkit/commit/15f6b61b63632dabc561aa888ffd5f879999b8c0
