### ISSUE TITLE
Command toolkit:build-dist fails when composer.json references local patches

### ISSUE THREAD

**Issue by vever001** [ec-europa/ssk#176]
Hi,

I have a bunch of local patches (not ideal I know but this is an inherited project) to apply in composer.json.
The `toolkit:build-dist dist` fails when patching because it does not copy the `patches` folder I have in the project root to the dist folder, before running composer install.

As suggested by @jonhy81, copying a `resources` folder as well and referencing e.g: `resources/patches/patch1.patch` is one solution.

**Comment by ghost** [comment]
Should be resolved with 4.0.0-beta9. Closing issue.
