### ISSUE TITLE
Fix grumphp conventions.

### ISSUE THREAD

**Issue by voidtek** [ec-europa/ssk#185]
The toolkit is not a drupal module but a library.
The grumphp.yml should be updated and all the files.
https://github.com/ec-europa/toolkit/blob/release/4.x/grumphp.yml.dist

And the file https://github.com/ec-europa/toolkit/blob/release/4.x/.editorconfig

**Comment by ghost** [comment]
What conventions would you suggest @voidtek ?

**Comment by ghost** [comment]
Created MULTISITE and PR:
- https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-22243
- https://github.com/ec-europa/toolkit/pull/218

**Comment by jonhy81** [comment]
Fixed in #218
