### ISSUE TITLE
Why does help.xml replace hyphens to underscores in db name?

### ISSUE THREAD

**Issue by cherouvim** [ec-europa/ssk#192]
If I use the following in the props file:
```
db.name = foo-db
```
then https://github.com/ec-europa/toolkit/blob/release/3.x/includes/phing/build/help.xml#L39 will change that to `foo_db`.

Why is this needed? Is it a convention of EU projects to not contain hyphens on their MySQL db names?

Drush (at least 8) seems to have not problem with that since, I suppose that, it escapes the db name with backticks. So this works:
```
jim@whatever:/tmp$ drush sqlq --db-url=mysql://foo-user:foo-password@localhost/foo-db "select 123"
123
```

**Comment by ghost** [comment]
Hi @cherouvim , I'm can't fully remember why I changed the db name to contain underscores only. 

If you would like to have this changed we can open a ticket for you in MULTISITE.
