### ISSUE TITLE
Command toolkit:build-dist copies untracked files

### ISSUE THREAD

**Issue by vever001** [ec-europa/ssk#236]
The toolkit:build-dist currently uses `rsync` and as such, copies everything, including untracked files.
In some cases this can be quite a problem because it copies gitignored files as well which are not meant to be copied.

I propose to use `git archive` instead of `rsync`, which simplifies quite a bit the dist build and makes it faster.

**Comment by ghost** [comment]
Will continue this in pull request https://github.com/ec-europa/toolkit/pull/238

**Comment by ghost** [comment]
Closing as this was released in 4.0.4
