### ISSUE TITLE
Drupal 8.8 deprecated "$config_directories['sync']"

### ISSUE THREAD

**Issue by vever001** [ec-europa/ssk#271]
At https://github.com/ec-europa/toolkit/blob/release/4.x/src/TaskRunner/Commands/DrupalCommands.php#L153

See 
- https://www.drupal.org/node/3018145
- https://www.drupal.org/docs/8/configuration-management/changing-the-storage-location-of-the-sync-directory#s-syntax-changes-in-drupal-880

**Comment by claudiu-cristea** [comment]
I've opened MULTISITE-23745. This should be closed.

**Comment by vever001** [comment]
Thanks @claudiu-cristea, closing this.
