### ISSUE TITLE
`toolkit:download-dump` should stop on failure

### ISSUE THREAD

**Issue by pfrenssen** [ec-europa/ssk#278]
When I execute `toolkit:download-dump` without having valid credentials I am getting the following error:

```
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="ASDA"
Reusing existing connection to asda.fpfis.tech.ec.europa.eu:443.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
 [Exec]  Exit code 6  Time 0.398s

Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in ./toolkit/src/TaskRunner/Commands/CloneCommands.php on line 175
```

If a 401 error occurs, then the command should exit with an error code rather than try to continue with non-existing data.

**Comment by jonhy81** [comment]
Hi @pfrenssen , for support with toolkit or drone, please open a ticket in JIRA using the board [DQA](https://webgate.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=5797), thanks for your comprehension.
