### ISSUE TITLE
False positive rule failure on PHPCS, with public folder path

### ISSUE THREAD

**Issue by lramarojaona** [ec-europa/ssk#282]
Hi, I'm getting a failure with a rule which says:
` 120 | ERROR | Internal hardcoded paths are not allowed. Please use
     |       | variable_get('file_public|private|temporary_path').`
https://drone.fpfis.eu/ec-europa/c4dweb-reference/2655/9

while my code is using variable_get:
`  if (!empty($options['prefix']) && strpos($path, variable_get('file_public_path', 'sites/default/files')) === 0) {
    $options['prefix'] = '';
  }`

I'll remove the sites/default/files for now, so it passes the test, but I guess this should be fixed.

Best regards.

**Comment by jonhy81** [comment]
Hi @lramarojaona , for support with toolkit or drone, please open a ticket in JIRA using the board [DQA](https://webgate.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=5797), thanks for your comprehension.
