### ISSUE TITLE
Toolkit 4.1 code fails to pass the static analysis test

### ISSUE THREAD

**Issue by skounis** [ec-europa/ssk#293]
![Annotation 2020-07-27 104545](https://user-images.githubusercontent.com/690575/88525110-7d594f00-cffa-11ea-926c-64f1f221d8ba.png)

**Comment by jonhy81** [comment]
Hi @skounis , for support with toolkit or drone, please open a ticket in JIRA using the board [DQA](https://webgate.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=5797), thanks for your comprehension.
